# Generated by Django 2.2.5 on 2020-01-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_teaching',
            field=models.ManyToManyField(blank=True, to='DB.Subject'),
        ),
    ]
