# Generated by Django 2.2.5 on 2020-01-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20200108_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='DB.Subject'),
        ),
    ]
