# Generated by Django 2.2.5 on 2020-01-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_auto_20200109_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectallocation',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.AcademicYear'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='class_room',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='DB.ClassRoom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.Stream'),
        ),
    ]
