# Generated by Django 2.2.5 on 2020-01-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_auto_20200109_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectallocation',
            name='academic_year',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='DB.AcademicYear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='term',
            field=models.CharField(blank=True, choices=[('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three')], max_length=10, null=True),
        ),
    ]
