# Generated by Django 2.2.5 on 2020-01-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_auto_20200109_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='term_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
